extends SceneTree
## verify_stamp — STREAM-SCHED R7 (docs/COSMOS-STREAM-SCHED-DESIGN.md §2.5 / §9.6) truth gate.
##
## R1 (FP_COLBULK) trades appearance for speed: its deep fill_area writes plain stone/deepslate and drops
## the interior strata/ore variants. verify_colbulk therefore has to gate it with an EXPOSURE oracle ("the
## loss is real but invisible"). R7 makes that trade unnecessary — the scatter pass puts every variant back
## — so this gate asks the one question that admits no judgement call:
##
##   G-ST-EQUAL   the load-bearing gate. For every block in the sweep, the buffer generated with
##                FP_COLBULK + FP_STAMP ON is BYTE-IDENTICAL, cell for cell, to the buffer generated by
##                the same generator with both flags OFF (the shipped per-cell path). Not "invisibly
##                different" — EQUAL. The reference is produced by flipping the generator's own flag
##                instance vars between two generate_block calls on the SAME generator, so the two runs
##                share every frozen table, ARID bake and code path except the fill+stamp itself.
##   G-ST-COVER   the sweep actually exercises the machinery: the fill+stamp path must have written a
##                material the plain fill cannot produce (a strata/ore variant) in at least one block,
##                and the sweep must span deep stone, the deepslate band, the −24..−16 dither rows and
##                the sub-−59 bedrock rows. A gate that passes on blocks where nothing fires proves
##                nothing — this is what stops G-ST-EQUAL being vacuously green.
##   G-ST-SHARED  the gather and the scatter agree on blob parameters because they CALL the same statics.
##                Pinned directly: over a lattice sweep, _strata_at/_ore_at's answer (via generated_cell)
##                is reproduced from strata_blob/ore_blob/strata_variant_of by the scatter's own formula.
##   G-ST-CLAMP   the containment premise R7 rides on, asserted rather than assumed: for every lattice
##                cell in a wide sweep, centre−r >= cell_lo and centre+r <= cell_lo+L. NOTE the plus face
##                reaches cell_lo+L, which is the NEXT cell's first cell — the blob bleeds by exactly one
##                cell, the gather truncates that bleed, and the scatter must clip to the cell to match.
##                This gate pins the bleed at EXACTLY one so the clip stays correct if a radius/pitch moves.
##
## Requires FP_COLBULK ON and FP_STAMP ON (consts): run with both sed-toggled true, e.g.
##   sed -i 's/const FP_STAMP := false/const FP_STAMP := true/' godot/src/cosmos/cube_sphere.gd
##   docker/engine/bin/godot.linuxbsd.editor.x86_64 --headless --path godot --script res://src/tools/verify_stamp.gd
## Runs in FLAT mode (gen_facet < 0 → the ridge guard self-disables), so it needs no faceted atlas.

var _pass := 0
var _fail := 0

func _ok(c: bool, m: String) -> void:
	if c:
		_pass += 1
		print("  PASS: %s" % m)
	else:
		_fail += 1
		print("  FAIL: %s" % m)

func _gen_into(gen: Object, origin: Vector3i) -> Object:
	var buf: Object = ClassDB.instantiate("VoxelBuffer")
	buf.call("create", 16, 16, 16)
	buf.call("set_channel_depth", 0, 1)          # DEPTH_16_BIT (matches the live TYPE channel)
	buf.call("fill", 0, 0)
	gen.call("generate_block", buf, Vector3(origin.x, origin.y, origin.z), 0)
	return buf

func _initialize() -> void:
	print("=== verify_stamp (STREAM-SCHED R7: lossless blob scatter — hard equality gate) ===")
	if not CubeSphere.FP_STAMP:
		print("  FAIL: CubeSphere.FP_STAMP is false — sed-toggle it true to run this gate.")
		print("==== VERIFY: 0 passed, 1 failed ===="); quit(1); return
	if not CubeSphere.FP_COLBULK:
		print("  FAIL: CubeSphere.FP_COLBULK is false — FP_STAMP stamps ITS fills; sed-toggle it true too.")
		print("==== VERIFY: 0 passed, 1 failed ===="); quit(1); return
	if not ClassDB.class_exists("VoxelTerrain"):
		print("  FAIL: godot_voxel module absent (ClassDB has no VoxelTerrain) — this gate needs the module binary.")
		print("==== VERIFY: 0 passed, 1 failed ===="); quit(1); return

	TerrainConfig.warm_up()

	# --- G-ST-CLAMP: the containment premise, before anything rests on it ------------------------------
	var sl := TerrainConfig.strata_lattice()
	var ol := TerrainConfig.ore_lattice()
	var clamp_bad := 0
	var bleed := 0                                # max cells a blob reaches PAST its own lattice cell
	for lx in range(-40, 41):
		for ly in range(-12, 9):
			for lz in range(-40, 41):
				var sb := TerrainConfig.strata_blob(lx, ly, lz)
				if sb.w != 0:
					if sb.x - sb.w < lx * sl or sb.y - sb.w < ly * sl or sb.z - sb.w < lz * sl:
						clamp_bad += 1            # minus face escaped — the scatter's lower clip would be wrong
					bleed = maxi(bleed, maxi(maxi(sb.x + sb.w - (lx * sl + sl - 1), sb.y + sb.w - (ly * sl + sl - 1)), sb.z + sb.w - (lz * sl + sl - 1)))
				var ob := TerrainConfig.ore_blob(lx, ly, lz)
				if ob.w != 0:
					if ob.x - ob.w < lx * ol or ob.y - ob.w < ly * ol or ob.z - ob.w < lz * ol:
						clamp_bad += 1
					bleed = maxi(bleed, maxi(maxi(ob.x + ob.w - (lx * ol + ol - 1), ob.y + ob.w - (ly * ol + ol - 1)), ob.z + ob.w - (lz * ol + ol - 1)))
	_ok(clamp_bad == 0, "G-ST-CLAMP: no blob escapes its lattice cell on the MINUS face (%d violations)" % clamp_bad)
	_ok(bleed == 1, "G-ST-CLAMP: PLUS-face bleed is exactly 1 cell (measured %d) — the gather truncates it, the scatter clips to match" % bleed)

	var mod: Node3D = (load("res://src/world/voxel_module/module_world.gd").new()) as Node3D
	get_root().add_child(mod)
	var ok_setup: bool = bool(mod.call("setup"))
	_ok(ok_setup, "setup: module_world built the flat terrain + baked library")
	if not ok_setup:
		print("==== VERIFY: %d passed, %d failed ====" % [_pass, _fail]); quit(1); return

	var gb: Object = mod.call("get_generator")
	_ok(bool(gb.get("fp_colbulk")), "setup: shipped generator has fp_colbulk ON (flag sed-toggled)")
	_ok(bool(gb.get("fp_stamp")), "setup: shipped generator has fp_stamp ON (flag sed-toggled)")
	var stone_arid := int(gb.get("bulk_stone_arid"))
	var deep_arid := int(gb.get("bulk_deepslate_arid"))
	_ok(stone_arid >= 0 and deep_arid >= 0, "setup: fill ARIDs baked (stone=%d, deepslate=%d)" % [stone_arid, deep_arid])

	# --- the sweep. Deliberately spans every class the stamp must respect: deep stone (above −16), the
	# −24..−16 dither rows, the deepslate region, the sub-−59 bedrock rows, the surface itself, shorelines
	# and the MOUNTAINS massifs (amplitude 92 — the steepest relief the generator can make, hence the
	# deepest per-column deep_top spread within one block).
	var origins: Array[Vector3i] = []
	for gx in range(-3, 4):
		for gz in range(-3, 4):
			var ox := gx * 16 * 7                      # a coprime-ish stride: many distinct biomes/columns
			var oz := gz * 16 * 5
			var gy := int(TerrainConfig.column_profile(ox + 8, oz + 8).x)
			for dy in [1, 0, -1, -2, -3]:              # surface, and 4 blocks down through the bands
				origins.append(Vector3i(ox, floori(gy / 16.0) * 16 + dy * 16, oz))
			origins.append(Vector3i(ox, -16, oz))      # the −24..−16 dither band straddler
			origins.append(Vector3i(ox, -32, oz))      # wholly deepslate
			origins.append(Vector3i(ox, -64, oz))      # the sub-−59 bedrock rows

	# --- G-ST-EQUAL: fill+stamp == per-cell, cell for cell -------------------------------------------
	# The reference flips fp_colbulk/fp_stamp OFF on the SAME generator instance, so the only difference
	# between the two runs is the fill+stamp itself — every frozen table and ARID bake is shared.
	var mismatch := 0
	var checked := 0
	var first := ""
	var variant_cells := 0                        # G-ST-COVER: cells the plain fill could NOT have produced
	for origin: Vector3i in origins:
		var got: Object = _gen_into(gb, origin)
		gb.set("fp_colbulk", false)
		gb.set("fp_stamp", false)
		var want: Object = _gen_into(gb, origin)
		gb.set("fp_colbulk", true)
		gb.set("fp_stamp", true)
		for ly in range(16):
			for lz in range(16):
				for lx in range(16):
					var a := int(got.call("get_voxel", lx, ly, lz, 0))
					var b := int(want.call("get_voxel", lx, ly, lz, 0))
					checked += 1
					var wy := origin.y + ly
					if wy < -16 - 16 and a != stone_arid and a != deep_arid and a != 0:
						variant_cells += 1        # deep, and not one of the two plain fill materials
					if a != b:
						mismatch += 1
						if first == "":
							first = "(%d,%d,%d) got arid %d want %d" % [origin.x + lx, wy, origin.z + lz, a, b]
	_ok(mismatch == 0, "G-ST-EQUAL: fill+stamp is BYTE-IDENTICAL to per-cell over %d blocks / %d cells (%d mismatches%s)"
		% [origins.size(), checked, mismatch, ("" if first == "" else "; first " + first)])
	_ok(variant_cells > 0, "G-ST-COVER: the sweep contains deep cells the plain fill cannot produce — strata/ore variants stamped (%d)" % variant_cells)

	# --- G-ST-SHARED: the two paths derive blob parameters from ONE source ---------------------------
	# Reproduce _strata_at's answer from the SCATTER's formula (lattice cell -> strata_blob -> sphere test
	# -> strata_variant_of) and compare against the gather, which reaches the same statics through
	# generated_cell. If someone re-implements either side independently, this fails.
	var shared_bad := 0
	var shared_hits := 0
	for i in range(4000):
		var x := (i * 7919) % 2000 - 1000
		var y := -(i * 31) % 80 - 20
		var z := (i * 104729) % 2000 - 1000
		var lx := floori(x / float(sl))
		var ly := floori(y / float(sl))
		var lz := floori(z / float(sl))
		var sb := TerrainConfig.strata_blob(lx, ly, lz)
		var want_var := -1
		if sb.w != 0:
			var dx := x - sb.x
			var dy := y - sb.y
			var dz := z - sb.z
			if dx * dx + dy * dy + dz * dz <= sb.w * sb.w:
				want_var = TerrainConfig.strata_variant_of(lx, ly, lz, sb.y)
		if want_var < 0:
			continue
		shared_hits += 1
		# The gather's own answer, via the shipped _deep_family composition.
		var host := TerrainConfig.deep_family_at(x, y, z)
		var base := BlockCatalog.STONE if y > -16 else host
		if y > -16:
			if host != want_var:
				shared_bad += 1
		elif y < -24:
			# deepslate region: the variant wins only if it is a deep pocket
			var expect := want_var if TerrainConfig.deep_pocket_variant(want_var) else base
			if TerrainConfig.deep_pocket_variant(want_var) and host != want_var:
				shared_bad += 1
	_ok(shared_hits > 0, "G-ST-SHARED: the lattice sweep landed inside strata blobs (%d hits)" % shared_hits)
	_ok(shared_bad == 0, "G-ST-SHARED: scatter-formula blob params reproduce the gather's _strata_at exactly (%d disagreements)" % shared_bad)

	print("==== VERIFY: %d passed, %d failed ====" % [_pass, _fail])
	quit(0 if _fail == 0 else 1)
